FROM maven:3.9.8-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml ./
COPY scraper-common ./scraper-common
COPY scraper-api ./scraper-api
COPY scraper-worker ./scraper-worker
COPY scraper-scheduler ./scraper-scheduler
RUN mvn -q -pl scraper-worker -am -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/scraper-worker/target/scraper-worker-1.0.0.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/app.jar"]
