apiVersion: v1
kind: Secret
metadata:
  name: scraper-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  api-key: {{ .Values.apiKey | quote }}
